### ISSUE TITLE
can't get input parameters?

### ISSUE THREAD

**Issue by zhjf0111** [ShareCat/STM32CommandLine#1]
the shell works well when there is no parameters, but report "wrong cmd" when a command following by a parameter.

**Comment by zhjf0111** [comment]
Sorry, I just found the solution!

**Comment by ShareCat** [comment]
sorry, I just got this message.

as for your question, you can get the following parameter from the "void *para",  you can see the solution from this LED example function: "uint8_t CLI_LED(void *para, uint8_t len)"
