### ISSUE TITLE
非常感谢这么棒的shell分享

### ISSUE THREAD

**Issue by a1123622944** [ShareCat/STM32CommandLine#2]
非常感谢这么棒的shell分享,但不知道为什么  其中上下左右健没有效果，我debug看了一下 好像是我的stm32并没有读到上下左右键的输入(判断不了大于8Bit的键,上下左右健应该是大于8bit的值)。期待shell更多功能的完善，再次感谢分享

**Comment by a1123622944** [comment]
非常期待有login的效果

**Comment by ShareCat** [comment]
非常感谢你的使用以及你的建议~

1、上下健的功能是有的，用于查询历史记录，历史记录个数可以自由配置。
2、左右健的功能目前没有，因为写这个shell一开始的初衷是简单，资源小，实用，加上感觉左右键单独用于调整输入光标位置有点费资源。。就没有加上这个功能。但后续可能会加上左右键的功能。做成像历史记录的功能一样，通过宏配置是否启用这一功能。
3、login功能马上就要发布了，已经在测试阶段。

**Comment by ShareCat** [comment]
> 非常期待有login的效果

非常感谢你的使用以及你的建议~

1、上下健的功能是有的，用于查询历史记录，历史记录个数可以自由配置。
2、左右健的功能目前没有，因为写这个shell一开始的初衷是简单，资源小，实用，加上感觉左右键单独用于调整输入光标位置有点费资源。。就没有加上这个功能。但后续可能会加上左右键的功能。做成像历史记录的功能一样，通过宏配置是否启用这一功能。
3、login功能马上就要发布了，已经在测试阶段。
