### ISSUE TITLE
大佬好，能不能介绍下怎么使用STM32的USB CDC 的VCP下移植的方法

### ISSUE THREAD

**Issue by shark910** [ShareCat/STM32CommandLine#4]
大佬好，能不能介绍下怎么使用STM32的USB CDC 的VCP下移植的方法
例如
```// HAL_StatusTypeDef status = HAL_UART_Transmit(huart_shell, (uint8_t *)data, len, 100);
    CDC_Transmit_FS((uint8_t *)data,len);```

**Comment by ShareCat** [comment]
> 大佬好，能不能介绍下怎么使用STM32的USB CDC 的VCP下移植的方法 例如
> 
> ```
>     CDC_Transmit_FS((uint8_t *)data,len);```
> ```

把你的工程发过来，我移植好了给你

**Comment by shark910** [comment]
我修改了\Core\Src\sys_command_line.c的文件
然后修改了，usbd_cdc_if.c中的CDC_Receive_F函数
好像就可以用了，感谢大佬的回复
